-- ORACLE
/*
SELECT SUBSTR(PRODUCT_CODE, 1, 2) AS CATEGORY, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY SUBSTR(PRODUCT_CODE, 1, 2)
ORDER BY SUBSTR(PRODUCT_CODE, 1, 2);
*/

SELECT P.CATEGORY, COUNT(*) AS PRODUCTS
FROM (SELECT SUBSTR(PRODUCT_CODE, 1, 2) AS CATEGORY
      FROM PRODUCT) P
GROUP BY P.CATEGORY
ORDER BY P.CATEGORY;
