-- ORACLE
-- 방법 2
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INSTR(UPPER(NAME), 'EL') > 0
    AND ANIMAL_TYPE = 'Dog'
ORDER BY NAME ASC;

-- 방법 1
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE UPPER(NAME) LIKE '%EL%'
    AND ANIMAL_TYPE = 'Dog'
ORDER BY NAME ASC;
