-- ORACLE
SELECT P.PRODUCT_CODE, O.SUM * P.PRICE AS SALES
FROM (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SUM
        FROM OFFLINE_SALE
        GROUP BY PRODUCT_ID) O, PRODUCT P
WHERE O.PRODUCT_ID = P.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE;
