-- ORACLE
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B, BOOK_SALES S
WHERE TO_CHAR(S.SALES_DATE, 'YYYY-MM') = '2022-01'
    AND B.BOOK_ID = S.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;
