-- ORACLE
-- SELECT : ID, 닉네임, 거래금액
-- ID로 join
-- WHERE 조건 : (1) 거래 완료 & (2) 총금액 70만 이상
-- 정렬 : 거래금액 오름차순
SELECT U.USER_ID, U.NICKNAME, SUB.TOTAL AS TOTAL_SALES
FROM (SELECT WRITER_ID, SUM(PRICE) AS TOTAL
      FROM USED_GOODS_BOARD
      WHERE STATUS = 'DONE'
      GROUP BY WRITER_ID) SUB, USED_GOODS_USER U
WHERE SUB.WRITER_ID = U.USER_ID
    AND SUB.TOTAL >= 700000
ORDER BY TOTAL_SALES;
