-- ORACLE
SELECT SUB.INGREDIENT_TYPE AS INGREDIENT_TYPE, SUM(SUB.TOTAL_ORDER) AS TOTAL_ORDER
FROM (SELECT F.TOTAL_ORDER, I.INGREDIENT_TYPE
    FROM FIRST_HALF F, ICECREAM_INFO I
    WHERE F.FLAVOR = I.FLAVOR) SUB
GROUP BY SUB.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;
