-- ORACLE
SELECT F1.CATEGORY, F1.PRICE, F1.PRODUCT_NAME
FROM FOOD_PRODUCT F1, (SELECT CATEGORY, MAX(PRICE) AS PRICE
                        FROM FOOD_PRODUCT
                        GROUP BY CATEGORY) F2
WHERE F1.CATEGORY = F2.CATEGORY
    AND F1.PRICE = F2.PRICE
    AND F1.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY F1.PRICE DESC;
