-- Oracle, MySQL
SELECT M.FOOD_TYPE ,R.REST_ID, R.REST_NAME, M.FAVORITES
FROM (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE) M, REST_INFO R
WHERE M.FOOD_TYPE = R.FOOD_TYPE
    AND M.FAVORITES = R.FAVORITES
ORDER BY M.FOOD_TYPE DESC;
